# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UmengShareDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UmengShareDemo


    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'



  target 'UmengShareDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UmengShareDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
