# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '111111' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 111111
    pod 'YYModel', '~> 1.0.4'

end
