# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayToolsDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayToolsDemo
    pod 'WechatOpenSDK'
    pod 'SVProgressHUD', '~> 2.0.3'

end
